# Generated by Django 6.0.6 on 2026-08-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_rates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
