# Generated by Django 6.0.6 on 2026-08-07 00:26

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='current',
            field=models.DecimalField(decimal_places=2, default=builtins.print, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
