# Generated by Django 6.0.6 on 2026-08-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_price_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
