# Generated by Django 6.0.6 on 2026-08-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_price_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='current',
        ),
    ]
