# Generated by Django 6.0.6 on 2026-08-07 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_price_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('product', 'user')},
        ),
    ]
