# Generated by Django 6.0.6 on 2026-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_ratings_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
