# Generated by Django 6.0.6 on 2026-08-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_price_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rates',
        ),
    ]
