# Generated by Django 6.0.6 on 2026-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rates',
            field=models.ManyToManyField(blank=True, related_name='product_ratings', to='products.ratings'),
        ),
    ]
