# Generated by Django 5.2.5 on 2026-07-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_personalspace_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalspace',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/photo.jpg', upload_to='profile/'),
        ),
    ]
